In [1]:
import sys
print(sys.executable)

c:\Users\cocoh\Downloads\heart_failure_prediction\.venv\Scripts\python.exe

Import libraries

In [27]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn.metrics as metrics

Import dataset

In [28]:
df = pd.read_csv('heart.csv')

Data Preprocessing

In [11]:
df.shape

(918, 12)

In [12]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='str')

In [13]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

isnull(): 
This means there is no null in this dataset

In [14]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 86.2 KB

In [16]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [17]:
categorical_data =df.select_dtypes(include='object')

C:\Users\cocoh\AppData\Local\Temp\ipykernel_14648\1648221971.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_data =df.select_dtypes(include='object')

In [18]:
categorical_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Sex             918 non-null    str
 1   ChestPainType   918 non-null    str
 2   RestingECG      918 non-null    str
 3   ExerciseAngina  918 non-null    str
 4   ST_Slope        918 non-null    str
dtypes: str(5)
memory usage: 36.0 KB

In [29]:
pd.get_dummies(categorical_data)

,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,False,True,False,True,False,False,False,True,False,True,False,False,False,True
1,True,False,False,False,True,False,False,True,False,True,False,False,True,False
2,False,True,False,True,False,False,False,False,True,True,False,False,False,True
3,True,False,True,False,False,False,False,True,False,False,True,False,True,False
4,False,True,False,False,True,False,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,False,True,False,False,False,True,False,True,False,True,False,False,True,False
914,False,True,True,False,False,False,False,True,False,True,False,False,True,False
915,False,True,True,False,False,False,False,True,False,False,True,False,True,False
916,True,False,False,True,False,False,True,False,False,True,False,False,True,False
917,False,True,False,False,True,False,False,True,False,True,False,False,False,True

In [20]:
df = pd.concat([df,pd.get_dummies(categorical_data)],axis=1)

In [21]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,M,ATA,140,289,0,Normal,172,N,0.0,...,False,False,False,True,False,True,False,False,False,True
1,49,F,NAP,160,180,0,Normal,156,N,1.0,...,True,False,False,True,False,True,False,False,True,False
2,37,M,ATA,130,283,0,ST,98,N,0.0,...,False,False,False,False,True,True,False,False,False,True
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,...,False,False,False,True,False,False,True,False,True,False
4,54,M,NAP,150,195,0,Normal,122,N,0.0,...,True,False,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,...,False,True,False,True,False,True,False,False,True,False
914,68,M,ASY,144,193,1,Normal,141,N,3.4,...,False,False,False,True,False,True,False,False,True,False
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,...,False,False,False,True,False,False,True,False,True,False
916,57,F,ATA,130,236,0,LVH,174,N,0.0,...,False,False,True,False,False,True,False,False,True,False
917,38,M,NAP,138,175,0,Normal,173,N,0.0,...,True,False,False,True,False,True,False,False,False,True

Drop the original categorical text columns (`Sex`, `ChestPainType`, `RestingECG`, `ExerciseAngina`, and `ST_Slope`) and replaced by their encoded numerical equivalents

In [34]:
# df.drop(['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope'],axis=1,inplace=True)
df = pd.get_dummies(df, dtype=int)
df

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,1,0,0,...,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1
3,48,138,214,0,108,1.5,1,1,0,1,...,0,0,0,1,0,0,1,0,1,0
4,54,150,195,0,122,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0
914,68,144,193,1,141,3.4,1,0,1,1,...,0,0,0,1,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,0,1,1,...,0,0,0,1,0,0,1,0,1,0
916,57,130,236,0,174,0.0,1,1,0,0,...,0,0,1,0,0,1,0,0,1,0
917,38,138,175,0,173,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1

In [35]:
# Calculate the median from the NON-ZERO values
non_zero_bp = df[df['RestingBP'] > 0]['RestingBP']
bp_median = non_zero_bp.median()
print(f"Median RestingBP (non-zero values): {bp_median}") 

# Replace 0s with the calculated median
df['RestingBP'] = df['RestingBP'].replace(0, bp_median)

# Verify the fix- Check for zeros and new statistics
print(f"Number of zeros in RestingBP after replacement: {(df['RestingBP'] == 0).sum()}")
print("\nNew Summary Statistics for RestingBP:")
print(df['RestingBP'].describe())

Median RestingBP (non-zero values): 130.0
Number of zeros in RestingBP after replacement: 0

New Summary Statistics for RestingBP:
count    918.000000
mean     132.538126
std       17.990127
min       80.000000
25%      120.000000
50%      130.000000
75%      140.000000
max      200.000000
Name: RestingBP, dtype: float64

In [36]:
# Calculate the median from the NON-ZERO values
non_zero_chl = df[df['Cholesterol'] > 0]['Cholesterol']
chl_median = non_zero_chl.median()
print(f"Median Cholesterol (non-zero values): {chl_median}") 

# Replace 0s with the calculated median
df['Cholesterol'] = df['Cholesterol'].replace(0, chl_median)

# Verify the fix- Check for zeros and new statistics
print(f"Number of zeros in Cholesterol after replacement: {(df['Cholesterol'] == 0).sum()}")
print("\nNew Summary Statistics for Cholesterol:")
print(df['Cholesterol'].describe())

Median Cholesterol (non-zero values): 237.0
Number of zeros in Cholesterol after replacement: 0

New Summary Statistics for Cholesterol:
count    918.000000
mean     243.204793
std       53.401297
min       85.000000
25%      214.000000
50%      237.000000
75%      267.000000
max      603.000000
Name: Cholesterol, dtype: float64

Drop the row where RestingBP value is 0

In [37]:
df.drop(df[df['RestingBP'] == 0].index, inplace=True)

Train-Test Split

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [43]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
print("Training set: ", X_train.shape, y_train.shape)
print("Test set: ", X_test.shape, y_test.shape)

Training set:  (734, 20) (734,)
Test set:  (184, 20) (184,)

Feature Scaling

In [44]:
scaler = StandardScaler()

# Fit ONLY on training data
X_train_scaled = scaler.fit_transform(X_train)
print("Train: ", X_train_scaled)

# Transform test data using the training scaler
X_test_scaled = scaler.transform(X_test)
print("Test: ", X_test_scaled)

Train:  [[ 0.9700116   0.3390158  -0.51402763 ... -0.26155954  0.98110491
  -0.86224587]
 [ 0.12202766 -1.26603098 -0.56933885 ... -0.26155954 -1.01925899
   1.15976201]
 [ 0.54601963 -0.15910217  1.71685831 ... -0.26155954  0.98110491
  -0.86224587]
 ...
 [ 0.54601963 -0.60187369 -0.21903445 ...  3.82322132 -1.01925899
  -0.86224587]
 [ 0.75801561 -0.43583437  0.86875291 ... -0.26155954 -1.01925899
   1.15976201]
 [-0.93795226  0.39436224 -0.38496811 ... -0.26155954 -1.01925899
   1.15976201]]
Test:  [[-0.83195427 -0.98929878 -0.14528615 ... -0.26155954  0.98110491
  -0.86224587]
 [ 0.44002164 -0.04840928 -0.38496811 ... -0.26155954 -1.01925899
   1.15976201]
 [ 0.65201762 -0.43583437  0.2418924  ... -0.26155954  0.98110491
  -0.86224587]
 ...
 [-0.51396029 -0.15910217 -0.14528615 ... -0.26155954  0.98110491
  -0.86224587]
 [ 0.54601963 -1.26603098 -0.108412   ... -0.26155954  0.98110491
  -0.86224587]
 [ 0.33402364 -1.54276319 -0.14528615 ... -0.26155954  0.98110491
  -0.86224587]]

Logistic Regression